"""Initial migration

Revision ID: fc9f9417f850
Revises: 
Create Date: 2026-01-23 21:50:32.738363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9f9417f850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_category_active', ['is_active'], unique=False)
        batch_op.create_index('idx_category_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_department_id', sa.Integer(), nullable=True),
    sa.Column('headquarters_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('headquarters_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('coverage_radius_km', sa.Float(), nullable=True),
    sa.Column('coverage_polygon', sa.JSON(), nullable=True),
    sa.Column('max_concurrent_incidents', sa.Integer(), nullable=True),
    sa.Column('current_active_incidents', sa.Integer(), nullable=True),
    sa.Column('dispatch_phone', sa.String(length=20), nullable=True),
    sa.Column('dispatch_email', sa.String(length=100), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('idx_department_active', ['is_active'], unique=False)
        batch_op.create_index('idx_department_location', ['headquarters_lat', 'headquarters_lng'], unique=False)
        batch_op.create_index('idx_department_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_type'), ['type'], unique=False)

    op.create_table('escalation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('severity_filter', sa.JSON(), nullable=True),
    sa.Column('category_filter', sa.JSON(), nullable=True),
    sa.Column('department_type_filter', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation_rules', schema=None) as batch_op:
        batch_op.create_index('idx_escalation_rule_active', ['is_active'], unique=False)
        batch_op.create_index('idx_escalation_rule_trigger', ['trigger_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalation_rules_trigger_type'), ['trigger_type'], unique=False)

    op.create_table('category_department_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('department_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'department_type', name='uq_category_dept_type')
    )
    with op.batch_alter_table('category_department_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_mapping_category_priority', ['category_id', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_department_mappings_category_id'), ['category_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_dispatcher', sa.Boolean(), nullable=False),
    sa.Column('is_responder', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('medical_info', sa.Text(), nullable=True),
    sa.Column('home_address', sa.String(length=255), nullable=True),
    sa.Column('home_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('home_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_department', ['department_id'], unique=False)
        batch_op.create_index('idx_user_on_duty', ['is_on_duty', 'is_available'], unique=False)
        batch_op.create_index('idx_user_role', ['is_staff', 'is_dispatcher', 'is_responder'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('anonymous_tracking_code', sa.String(length=20), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('address_formatted', sa.String(length=255), nullable=True),
    sa.Column('landmark_description', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatch_time', sa.DateTime(), nullable=True),
    sa.Column('acknowledge_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('closed_time', sa.DateTime(), nullable=True),
    sa.Column('dispatch_response_seconds', sa.Integer(), nullable=True),
    sa.Column('total_response_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_affected_people', sa.Integer(), nullable=True),
    sa.Column('requires_evacuation', sa.Boolean(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index('idx_incident_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_incident_location', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_incident_severity', ['severity'], unique=False)
        batch_op.create_index('idx_incident_status', ['status'], unique=False)
        batch_op.create_index('idx_incident_tracking', ['anonymous_tracking_code'], unique=False)
        batch_op.create_index('idx_incident_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_anonymous_tracking_code'), ['anonymous_tracking_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_incident_reports_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_pushed', sa.Boolean(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('is_emailed', sa.Boolean(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.Column('is_sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_type', ['type'], unique=False)
        batch_op.create_index('idx_notification_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('incident_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('allocation_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('en_route_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledgment_time_seconds', sa.Integer(), nullable=True),
    sa.Column('travel_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'department_id', name='uq_incident_department')
    )
    with op.batch_alter_table('incident_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_assignment_assigned_at', ['assigned_at'], unique=False)
        batch_op.create_index('idx_assignment_incident_dept', ['incident_id', 'department_id'], unique=False)
        batch_op.create_index('idx_assignment_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assignments_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assignments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assignments_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assignments_responder_id'), ['responder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assignments_status'), ['status'], unique=False)

    op.create_table('incident_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachment_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_attachments_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_attachments_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('incident_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('captured_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('captured_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_media', schema=None) as batch_op:
        batch_op.create_index('idx_media_type', ['media_type'], unique=False)
        batch_op.create_index('idx_media_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_media_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_media_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('incident_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_messages_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_incident_id', sa.Integer(), nullable=True),
    sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_incident_id'], ['incident_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('idx_resource_status', ['status'], unique=False)
        batch_op.create_index('idx_resource_type', ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_status'), ['status'], unique=False)

    op.create_table('safety_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('center_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('coverage_polygon', sa.JSON(), nullable=True),
    sa.Column('is_citywide', sa.Boolean(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('push_sent_count', sa.Integer(), nullable=True),
    sa.Column('sms_sent_count', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_active', ['is_active'], unique=False)
        batch_op.create_index('idx_alert_location', ['center_lat', 'center_lng'], unique=False)
        batch_op.create_index('idx_alert_severity', ['severity'], unique=False)
        batch_op.create_index('idx_alert_timing', ['active_from', 'active_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_alerts_severity'), ['severity'], unique=False)

    op.create_table('escalation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['incident_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['escalation_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation_logs', schema=None) as batch_op:
        batch_op.create_index('idx_escalation_log_incident', ['incident_id'], unique=False)
        batch_op.create_index('idx_escalation_log_triggered_at', ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalation_logs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalation_logs_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['incident_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index('idx_status_history_changed_at', ['changed_at'], unique=False)
        batch_op.create_index('idx_status_history_incident_changed', ['incident_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_incident_id'))
        batch_op.drop_index(batch_op.f('ix_status_history_changed_at'))
        batch_op.drop_index('idx_status_history_incident_changed')
        batch_op.drop_index('idx_status_history_changed_at')

    op.drop_table('status_history')
    with op.batch_alter_table('escalation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_logs_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_escalation_logs_incident_id'))
        batch_op.drop_index('idx_escalation_log_triggered_at')
        batch_op.drop_index('idx_escalation_log_incident')

    op.drop_table('escalation_logs')
    with op.batch_alter_table('safety_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_safety_alerts_alert_type'))
        batch_op.drop_index('idx_alert_timing')
        batch_op.drop_index('idx_alert_severity')
        batch_op.drop_index('idx_alert_location')
        batch_op.drop_index('idx_alert_active')

    op.drop_table('safety_alerts')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_status'))
        batch_op.drop_index(batch_op.f('ix_resources_department_id'))
        batch_op.drop_index('idx_resource_type')
        batch_op.drop_index('idx_resource_status')

    op.drop_table('resources')
    with op.batch_alter_table('incident_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_incident_messages_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_messages_created_at'))
        batch_op.drop_index('idx_message_incident_created')

    op.drop_table('incident_messages')
    with op.batch_alter_table('incident_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_media_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_incident_media_incident_id'))
        batch_op.drop_index('idx_media_uploaded_at')
        batch_op.drop_index('idx_media_type')

    op.drop_table('incident_media')
    with op.batch_alter_table('incident_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_attachments_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_incident_attachments_incident_id'))
        batch_op.drop_index('idx_attachment_uploaded_at')

    op.drop_table('incident_attachments')
    with op.batch_alter_table('incident_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_incident_assignments_responder_id'))
        batch_op.drop_index(batch_op.f('ix_incident_assignments_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_assignments_department_id'))
        batch_op.drop_index(batch_op.f('ix_incident_assignments_assigned_at'))
        batch_op.drop_index('idx_assignment_status')
        batch_op.drop_index('idx_assignment_incident_dept')
        batch_op.drop_index('idx_assignment_assigned_at')

    op.drop_table('incident_assignments')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('idx_notification_user_read')
        batch_op.drop_index('idx_notification_user_created')
        batch_op.drop_index('idx_notification_type')

    op.drop_table('notifications')
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_status'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_severity'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_category_id'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_anonymous_tracking_code'))
        batch_op.drop_index('idx_incident_user_created')
        batch_op.drop_index('idx_incident_tracking')
        batch_op.drop_index('idx_incident_status')
        batch_op.drop_index('idx_incident_severity')
        batch_op.drop_index('idx_incident_location')
        batch_op.drop_index('idx_incident_created_at')

    op.drop_table('incident_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_on_duty')
        batch_op.drop_index('idx_user_department')

    op.drop_table('users')
    with op.batch_alter_table('category_department_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_department_mappings_category_id'))
        batch_op.drop_index('idx_mapping_category_priority')

    op.drop_table('category_department_mappings')
    with op.batch_alter_table('escalation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_rules_trigger_type'))
        batch_op.drop_index('idx_escalation_rule_trigger')
        batch_op.drop_index('idx_escalation_rule_active')

    op.drop_table('escalation_rules')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_type'))
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index('idx_department_type')
        batch_op.drop_index('idx_department_location')
        batch_op.drop_index('idx_department_active')

    op.drop_table('departments')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index('idx_category_name')
        batch_op.drop_index('idx_category_active')

    op.drop_table('categories')
    # ### end Alembic commands ###
